version: "3.3"
services:
  mongodb:
    image: mongo:4.4.3
    container_name: mongodb
    ports:
      - target: 27017
        published: 27000
    volumes:
      - type: volume
        source: data
        target: /data/db
    networks:
      - dragon
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: "/run/secrets/db_username"
      MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/db_password"
    secrets:
      - db_username
      - db_password
    restart: always
  lianjia-scrapy:
    build: .
    image: lianjia-scrapy
    container_name: lianjia-scrapy
    depends_on:
      - mongodb
    networks:
      - dragon
    environment:
      DRAGON_TALON_DB_USERNAME_FILE: "/run/secrets/db_username"
      DRAGON_TALON_DB_PASSWORD_FILE: "/run/secrets/db_password"
    secrets:
      - db_username
      - db_password
    restart: always

volumes:
    data:

networks:
    dragon:

secrets:
  db_username:
    file: secrets/db_username.txt
  db_password:
    file: secrets/db_password.txt
