version: "3.3"
services:
  mongodb:
    image: mongo:4.4.3
    container_name: mongodb
    ports:
      - target: 27017
        published: 27000
    volumes:
      - type: volume
        source: data
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: "/run/secrets/mongo_root"
      MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/mongo_root_pwd"
    secrets:
      - mongo_root
      - mongo_root_pwd
    restart: always

volumes:
    data:

secrets:
  mongo_root:
    file: secrets/admin_username.txt
  mongo_root_pwd:
    file: secrets/admin_password.txt
