version: "3.3"
services:
  mongodb:
    image: mongo:4.4.3
    container_name: mongodb
    ports:
      - target: 27017
        published: 27000
    volumes:
      - type: volume
        source: data
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: "/run/secrets/db_username"
      MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/db_password"
    secrets:
      - db_username
      - db_password
    restart: always
  lianjia-scrapy:
    # TODO build: .
    image: python:3.7.8-slim-stretch
    container_name: lianjia-scrapy
    environment:
      DB_USERNAME_FILE: "/run/secrets/db_username"
      DB_PASSWORD_FILE: "/run/secrets/db_password"
    secrets:
      - db_username
      - db_password
    restart: always

volumes:
    data:

secrets:
  db_username:
    file: secrets/db_username.txt
  db_password:
    file: secrets/db_password.txt
